language: node_js
node_js:
  - "10"
before_script:
- cd webapp/
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- yarn install

script:
  - yarn build
  - yarn test
  - yarn coveralls
  - sh deploy.sh

env:
  global:
  - GH_REPO="marabesi/testable"
  - REACT_APP_BASE_NAME="/testable"