language: node_js
node_js:
  - "10"
before_script:
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- yarn install
- ./node_modules/.bin/cypress install

script:
  - yarn build
  - yarn test
  - yarn coveralls
  - sh deploy.sh
  - yarn cypress:run

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  global:
  - GH_REPO="marabesi/testable"
  - REACT_APP_BASE_NAME="/testable"