language: node_js
node_js:
  - "7"
  - "8"
  - "9"
before_script:
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- yarn install

script:
  - yarn test
  - yarn build

env:
  global:
  - GH_REPO="marabesi/testable"
  - REACT_APP_BASE_NAME="/testable"