language: node_js
node_js:
  - "7"
before_script:
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- npm install

script:
  - npm run test
  - npm run build

env:
  global:
  - GH_REPO="marabesi/testable"
  - REACT_APP_BASE_NAME="/testable"
branches:
  only:
  - master
after_script:
- sudo ./deploy.sh