language: node_js
node_js:
  - "12"
before_script:
- cd webapp/
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- npm install

script:
  - npm run build
  - npm run test
  - npm run coveralls

after_success:
  - if ["$TRAVIS_BRANCH" == "master"]; then sh deploy.sh; fi;

env:
  global:
  - GH_REPO="marabesi/testable"
  - REACT_APP_BASE_NAME="/testable"