version: '2'
services:
  webserver:
    image: nginx
    environment:
      - NODE_HOST=testable
      - NODE_PORT=5000
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./docker/nginx/:/nginx
    command: /bin/bash -c "envsubst < /nginx/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
  testable:
    extends:
      file: ./docker-compose.yml
      service: testable
    environment:
      - REACT_APP_FIREBASE_JSON=$REACT_APP_FIREBASE_JSON
      - REACT_APP_RANKING_API=$REACT_APP_RANKING_API
      - REACT_APP_SURVEY_URL=$REACT_APP_SURVEY_URL
      - REACT_APP_SHOW_SURVEY=$REACT_APP_SHOW_SURVEY
      - REACT_APP_DEBUG=$REACT_APP_DEBUG
    volumes:
      - ./webapp:/var/www/app
    command: npm run start
    stdin_open: true
    ports:
      - 5000:5000
  ranking:
    environment:
      - PORT=4000
    build:
      context: ./ranking-api
    user: 'node'
    volumes:
      - ./ranking-api:/var/www/ranking_api
    command: node index.js
    ports:
      - 4000:4000