version: '2'
services:
  webserver:
    image: nginx
    environment:
      - NODE_HOST=app
      - NODE_PORT=5000
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./docker/nginx/:/nginx
    command: /bin/bash -c "envsubst < /nginx/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
  app:
    environment:
      - PORT=5000
    image: node:10.18
    user: 'node'
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: sh -c "yarn && yarn build && yarn serve"